#!/bin/bash
case "$1" in
	"")
	Linux List
	;;
	"Alpine")
rm ~/.alpine
rm -rf ~/alpine-fs
rm ../usr/bin/alpine
	;;
        "Arch")
rm ~/.arch
rm -rf ~/arch-fs
rm ../usr/bin/arch
	;;
        "Centos")
rm ~/.centos
rm -rf ~/centos-fs
rm ../usr/bin/centos
	;;
        "Debian")
rm ~/.debian
rm -rf ~/debian-fs
rm ../usr/bin/debian
	;;
        "Fedora")
rm ~/.fedora
rm -rf ~/fedora-fs
rm ../usr/bin/fedora
	;;
        "Kali")
rm -rf ~/kali*
rm ../usr/bin/nh
rm ../usr/bin/nethunter
	;;
        "Manjaro")
rm ~/.manjaro
rm -rf ~/manjaro-fs
rm ../usr/bin/manjaro
	;;
        "Opensuse")
rm ~/.opensuse
rm -rf ~/opensuse-fs
rm ../usr/bin/opensuse
	;;
        "Parrot")
rm ~/.parrot
rm -rf ~/parrot*
rm ../usr/bin/parrot
	;;
        "Ubuntu")
rm ~/.ubuntu
rm -rf ~/ubuntu-fs
rm ../usr/bin/ubuntu
	;;
        "Void")
rm ~/.void
rm -rf ~/void-fs
rm ../usr/bin/void
	;;
        *)
Linux List
        ;;
esac
