#!/bin/bash
blk='\e[0;30m' red='\e[0;31m' grn='\e[0;32m' ylw='\e[0;33m'
blu='\e[0;34m' pur='\e[0;35m' cyn='\e[0;36m' wht='\e[0;37m'
clear
case "$1" in
	"")
	Linux List
	;;
	"Alpine")
clear
printf "\n"
printf "${blu}Welcome To Alpine Termux For Android\n"
printf "${red}> ${wht}https://github.com/wahasa/Alpine"
printf "\n\n\n"

printf "${ylw}• Alpine 3.17"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Alpine3.17\n"
printf "${blu}Versi  ${red}: ${grn}3.17.2\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"

printf "${ylw}• Alpine 3.16"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Alpine3.16\n"
printf "${blu}Versi  ${red}: ${grn}3.16.4\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"

printf "${ylw}• Alpine 3.15"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Alpine3.15\n"
printf "${blu}Versi  ${red}: ${grn}3.15.7\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"

printf "${ylw}• Alpine (Edge)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}AlpineDev\n"
printf "${blu}Versi  ${red}: ${grn}3.18 (20230208)\n"
printf "${blu}Status ${red}: ${grn}Development\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "AlpineDev")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Alpine/alpine.sh && chmod +x alpine.sh && ./alpine.sh
        ;;
        "Alpine3.15")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Alpine/alpine3.15.sh && chmod +x alpine3.15.sh && ./alpine3.15.sh
        ;;
        "Alpine3.16")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Alpine/alpine3.16.sh && chmod +x alpine3.16.sh && ./alpine3.16.sh
        ;;
        "Alpine3.17")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Alpine/alpine3.17.sh && chmod +x alpine3.17.sh && ./alpine3.17.sh
	;;
        "Arch")
clear
printf "\n"
printf "${wht}Welcome To Arch Termux For Android"
printf "\n\n\n"

printf "${ylw}• Arch 2022"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Arch2022\n"
printf "${blu}Versi  ${red}: ${grn}Build-20220810\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "Arch2022")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Arch/arch.sh && chmod +x arch.sh && ./arch.sh
	;;
        "Centos")
clear
printf "\n"
printf "${wht}Welcome To Centos Termux For Android"
printf "\n\n\n"

printf "${ylw}• CentOS 9 Stream"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Centos9\n"
printf "${blu}Versi  ${red}: ${grn}9 (20230216)\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Arm64,Amd64"
printf "\n\n"
printf "${ylw}• CentOS 8 Stream"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Centos8\n"
printf "${blu}Versi  ${red}: ${grn}8 (20220913)\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Not Available"
printf "\n\n"
printf "${ylw}• Centos 7"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Centos7\n"
printf "${blu}Versi  ${red}: ${grn}7.9-2009\n"
printf "${blu}Status ${red}: ${grn}Final Build\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "Centos7")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/CentOs/centos7.sh && chmod +x centos7.sh && ./centos7.sh
	;;
        "Centos8")
clear
echo ""
echo "Rootfs Not Available,."
echo ""
sleep 1
echo -n ""
echo -n "1"
sleep 1
echo -n "."
sleep 1
echo -n "."
sleep 1
echo -n "2"
sleep 1
echo -n "."
sleep 1
echo -n "."
sleep 1
echo -n "3"
sleep 1
echo -n "."
sleep 1
echo -n "."
sleep 1
echo -n ">"
sleep 2
echo ""
Install Centos
	;;
        "Centos9")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/CentOs/centos9.sh && chmod +x centos9.sh && ./centos9.sh
	;;
        "Debian")
clear
printf "\n"
printf "${blu}Welcome To Debian Termux For Android\n"
printf "${red}> ${wht}https://github.com/wahasa/Debian"
printf "\n\n\n"
printf "${ylw}• Debian (Bullseye)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Debian11\n"
printf "${blu}Versi  ${red}: ${grn}11.06\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${ylw}• Debian (Buster)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Debian10\n"
printf "${blu}Versi  ${red}: ${grn}10.13\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${ylw}• Debian (bookworm)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}DebianDev\n"
printf "${blu}Versi  ${red}: ${grn}Build-20230208\n"
printf "${blu}Status ${red}: ${grn}Development\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "Debian10")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Debian/debian10.sh && chmod +x debian10.sh && ./debian10.sh
        ;;
        "Debian11")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Debian/debian11.sh && chmod +x debian11.sh && ./debian11.sh
        ;;
        "DebianDev")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Debian/debian.sh && chmod +x debian.sh && ./debian.sh
	;;
        "Fedora")
clear
printf "\n"
printf "${blu}Welcome To Fedora Termux For Android\n"
printf "${red}> ${wht}https://github.com/wahasa/Fedora"
printf "\n\n\n"

printf "${ylw}• Fedora 38 (Container)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Fedora38\n"
printf "${blu}Versi  ${red}: ${grn}38.0.0\n"
printf "${blu}Status ${red}: ${grn}Pre-release\n"
printf "${blu}Rootfs ${red}: ${grn}Arm64,Amd64"
printf "\n\n"

printf "${ylw}• Fedora 37 (Container)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Fedora37\n"
printf "${blu}Versi  ${red}: ${grn}37.0.0\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Arm64,Amd64"
printf "\n\n"

printf "${ylw}• Fedora 36 (Container)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Fedora36\n"
printf "${blu}Versi  ${red}: ${grn}36.1.5\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "Fedora36")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Fedora/fedora36.sh && chmod +x fedora36.sh && ./fedora36.sh
        ;;
        "Fedora37")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Fedora/fedora37.sh && chmod +x fedora37.sh && ./fedora37.sh
        ;;
        "Fedora38")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Fedora/fedora38.sh && chmod +x fedora38.sh && ./fedora38.sh
	;;
        "Kali")
clear
printf "\n"
printf "${blu}Welcome To Kali Termux For Android\n"
printf "${red}> ${wht}https://github.com/wahasa/kali-linux"
printf "\n\n\n"

printf "${ylw}• Kali Nethunter"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Kali2022\n"
printf "${blu}Versi  ${red}: ${grn}2022.4\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "Kali2022")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Kali/kali2022.sh && chmod +x kali2022.sh && ./kali2022.sh
	;;
        "Manjaro")
clear
printf "\n"
printf "${wht}Welcome To Manjaro Termux For Android"
printf "\n\n\n"

printf "${ylw}• Manjaro 2023"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Manjaro2023\n"
printf "${blu}Versi  ${red}: ${grn}2023\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Arm64 (AArch64)"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "Manjaro2023")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Manjora/manjaro.sh && chmod +x manjaro.sh && ./manjaro.sh
	;;
        "Opensuse")
clear
printf "\n"
printf "${wht}Welcome To OpenSuse Termux For Android"
printf "\n\n\n"

printf "${ylw}• Opensuse Leap"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Opensuse15\n"
printf "${blu}Versi  ${red}: ${grn}15.4\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"

printf "${ylw}• Opensuse Tumbleweed"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Opensuse2022\n"
printf "${blu}Versi  ${red}: ${grn}2022\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "Opensuse15")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Opensuse/opensuse15.sh && chmod +x opensuse15.sh && ./opensuse15.sh
        ;;
        "Opensuse2022")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Opensuse/opensuse.sh && chmod +x opensuse.sh && ./opensuse.sh
	;;
        "Parrot")
clear
printf "\n"
printf "${wht}Welcome To Parrot Termux For Android"
printf "\n\n\n"

printf "${ylw}• Parrot 5.1 (Electro Ara)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Parrot5.1\n"
printf "${blu}Versi  ${red}: ${grn}5.1.2\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "Parrot5.1")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Parrot/parrot5.1.sh && chmod +x parrot5.1.sh && ./parrot5.1.sh
	;;
        "Ubuntu")
clear
printf "\n"
printf "${blu}Welcome To Ubuntu Termux For Android\n"
printf "${red}> ${wht}https://github.com/wahasa/Ubuntu"
printf "\n\n\n"
printf "${ylw}• Ubuntu (Lunar Lobster)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Ubuntu23.04\n"
printf "${blu}Versi  ${red}: ${grn}23.04\n"
printf "${blu}Status ${red}: ${grn}Pre-release\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${ylw}• Ubuntu (Kinetic Kudu)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Ubuntu22.10\n"
printf "${blu}Versi  ${red}: ${grn}22.10\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${ylw}• Ubuntu (Jammy Jellyfish)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Ubuntu22.04\n"
printf "${blu}Versi  ${red}: ${grn}22.04.1 lts\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "Ubuntu22.04")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Ubuntu/ubuntu22.04.sh && chmod +x ubuntu22.04.sh && ./ubuntu22.04.sh
        ;;
        "Ubuntu22.10")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Ubuntu/ubuntu22.10.sh && chmod +x ubuntu22.10.sh && ./ubuntu22.10.sh
        ;;
        "Ubuntu23.04")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Ubuntu/ubuntu23.04.sh && chmod +x ubuntu23.04.sh && ./ubuntu23.04.sh
	;;
        "Void")
clear
printf "\n"
printf "${wht}Welcome To Void Termux For Android"
printf "\n\n\n"

printf "${ylw}• Void 2022"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Void2022\n"
printf "${blu}Versi  ${red}: ${grn}2022\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "Void2022")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Void/void.sh && chmod +x void.sh && ./void.sh
	;;
        *)
Linux List
        ;;
esac
