#!/bin/bash
blk='\e[0;30m' red='\e[0;31m' grn='\e[0;32m' ylw='\e[0;33m'
blu='\e[0;34m' pur='\e[0;35m' cyn='\e[0;36m' wht='\e[0;37m'
clear
case "$1" in
	"")
	Linux List
	;;
	"Alpine")
clear
printf "\n"
printf "${wht}Welcome To Alpine Termux For Android"
printf "\n\n\n"
printf "${ylw}• Alpine 3.17"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Alpine3.17\n"
printf "${blu}Versi  ${red}: ${grn}3.17.0\n"
printf "${blu}Status ${red}: ${grn}Pre-release"
printf "\n\n"
printf "${ylw}• Alpine 3.16"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Alpine3.16\n"
printf "${blu}Versi  ${red}: ${grn}3.16.3\n"
printf "${blu}Status ${red}: ${grn}latest"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "Alpine3.16")
	echo "Sukses 1"
        ;;
        "Alpine3.17")
	echo "Sukses 2"
	;;
        "Debian")
clear
printf "\n"
printf "${wht}Welcome To Debian Termux For Android"
printf "\n\n\n"
printf "${ylw}• Debian 11 (Bullseye)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Debian11\n"
printf "${blu}Versi  ${red}: ${grn}11.05\n"
printf "${blu}Status ${red}: ${grn}latest"
printf "\n\n"
printf "${ylw}• Debian 10 (Buster)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Debian10\n"
printf "${blu}Versi  ${red}: ${grn}10.13\n"
printf "${blu}Status ${red}: ${grn}latest"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
	"Debian10")
	echo "Sukses 1"
	;;
	"Debian11")
	echo "Sukses 2"
	;;
        "Fedora")
clear
printf "\n"
printf "${wht}Welcome To Fedora Termux For Android"
printf "\n\n\n"
printf "${ylw}• Fedora 38"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Fedora38\n"
printf "${blu}Versi  ${red}: ${grn}38.0\n"
printf "${blu}Status ${red}: ${grn}Beta"
printf "\n\n"
printf "${ylw}• Fedora 37"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Fedora37\n"
printf "${blu}Versi  ${red}: ${grn}37.0\n"
printf "${blu}Status ${red}: ${grn}Pre-release"
printf "\n\n"
printf "${ylw}• Fedora 36"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Fedora36\n"
printf "${blu}Versi  ${red}: ${grn}36.1.5\n"
printf "${blu}Status ${red}: ${grn}latest"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
        ;;
        "Fedora36")
        echo "Sukses 1"
        ;;
        "Fedora37")
        echo "Sukses 2"
	;;
        "Fedora38")
        echo "Sukses 3"
	;;
        "Kali")
clear
printf "\n"
printf "${wht}Welcome To Kali Termux For Android"
printf "\n\n\n"
printf "${ylw}• Kali 2022"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Kali2022\n"
printf "${blu}Versi  ${red}: ${grn}2022.3\n"
printf "${blu}Status ${red}: ${grn}latest"
printf "\n\n"
printf "${ylw}• Kali 2021"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Kali2021\n"
printf "${blu}Versi  ${red}: ${grn}2021.4a\n"
printf "${blu}Status ${red}: ${grn}latest"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "Kali2021")
        echo "Sukses 1"
        ;;
        "Kali2022")
        echo "Sukses 2"
	;;
        "Parrot")
clear
printf "\n"
printf "${wht}Welcome To Parrot Termux For Android"
printf "\n\n\n"
printf "${ylw}• Parrot 5.1 (Electro Ara)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Parrot5.1\n"
printf "${blu}Versi  ${red}: ${grn}5.1.1\n"
printf "${blu}Status ${red}: ${grn}latest"
printf "\n\n"
printf "${ylw}• Parrot 5.0 (Electro Ara)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Parrot5.0\n"
printf "${blu}Versi  ${red}: ${grn}5.0.1\n"
printf "${blu}Status ${red}: ${grn}latest"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "Parrot5.0")
        echo "Sukses 1"
        ;;
        "Parrot5.1")
        echo "Sukses 2"
	;;
        "Ubuntu")
clear
printf "\n"
printf "${wht}Welcome To Ubuntu Termux For Android"
printf "\n\n\n"
printf "${ylw}• Ubuntu (Lunar Lobster)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Ubuntu23.04\n"
printf "${blu}Versi  ${red}: ${grn}23.04 lts\n"
printf "${blu}Status ${red}: ${grn}Beta"
printf "\n\n"
printf "${ylw}• Ubuntu (Kinetic Kudu)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Ubuntu22.10\n"
printf "${blu}Versi  ${red}: ${grn}22.10\n"
printf "${blu}Status ${red}: ${grn}latest"
printf "\n\n"
printf "${ylw}• Ubuntu (Jammy Jellyfish)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Ubuntu22.04\n"
printf "${blu}Versi  ${red}: ${grn}22.04.1\n"
printf "${blu}Status ${red}: ${grn}latest"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "Ubuntu22.04")
        echo "Sukses 1"
        ;;
        "Ubuntu22.10")
        echo "Sukses 2"
	;;
        *)
        ;;
esac
