#!/bin/bash
blk='\e[0;30m' red='\e[0;31m' grn='\e[0;32m' ylw='\e[0;33m'
blu='\e[0;34m' pur='\e[0;35m' cyn='\e[0;36m' wht='\e[0;37m'
clear
case "$1" in
	"")
	Linux List
	;;
	"Alpine")
clear
printf "\n"
printf "${wht}Welcome To Alpine Termux For Android"
printf "\n\n\n"

printf "${ylw}• Alpine 3.17"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Alpine3.17\n"
printf "${blu}Versi  ${red}: ${grn}3.17.0\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"

printf "${ylw}• Alpine 3.16"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Alpine3.16\n"
printf "${blu}Versi  ${red}: ${grn}3.16.3\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"

printf "${ylw}• Alpine 3.15"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Alpine3.15\n"
printf "${blu}Versi  ${red}: ${grn}3.15.6\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "Alpine3.15")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Alpine/alpine3.15.6.sh && chmod +x alpine3.15.6.sh && ./alpine3.15.6.sh
        ;;
        "Alpine3.16")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Alpine/alpine3.16.3.sh && chmod +x alpine3.16.3.sh && ./alpine3.16.3.sh
        ;;
        "Alpine3.17")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Alpine/alpine3.17.0.sh && chmod +x alpine3.17.0.sh && ./alpine3.17.0.sh
	;;
        "Debian")
clear
printf "\n"
printf "${wht}Welcome To Debian Termux For Android"
printf "\n\n\n"
printf "${ylw}• Debian (Bullseye)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Debian11.05\n"
printf "${blu}Versi  ${red}: ${grn}11.05\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${ylw}• Debian (Buster)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Debian10.13\n"
printf "${blu}Versi  ${red}: ${grn}10.13\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${ylw}• Debian (bookworm)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}DebianTest\n"
printf "${blu}Versi  ${red}: ${grn}Testing\n"
printf "${blu}Status ${red}: ${grn}Testing\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "Debian10.13")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Debian/debian10.13.sh && chmod +x debian10.13.sh && ./debian10.13.sh
        ;;
        "Debian11.05")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Debian/debian11.05.sh && chmod +x debian11.05.sh && ./debian11.05.sh
        ;;
        "DebianTest")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Debian/debian.sh && chmod +x debian.sh && ./debian.sh
	;;
        "Fedora")
clear
printf "\n"
printf "${wht}Welcome To Fedora Termux For Android"
printf "\n\n\n"

printf "${ylw}• Fedora 38 (Container)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Fedora38\n"
printf "${blu}Versi  ${red}: ${grn}38.0.0\n"
printf "${blu}Status ${red}: ${grn}Pre-release\n"
printf "${blu}Rootfs ${red}: ${grn}Arm64,Amd64"
printf "\n\n"

printf "${ylw}• Fedora 37 (Container)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Fedora37\n"
printf "${blu}Versi  ${red}: ${grn}37.0.0\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Arm64,Amd64"
printf "\n\n"

printf "${ylw}• Fedora 36 (Container)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Fedora36\n"
printf "${blu}Versi  ${red}: ${grn}36.1.5\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "Fedora36")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Fedora/fedora36.1.5.sh && chmod +x fedora36.1.5.sh && ./fedora36.1.5.sh
        ;;
        "Fedora37")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Fedora/fedora37.0.0.sh && chmod +x fedora37.0.0.sh && ./fedora37.0.0.sh
        ;;
        "Fedora38")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Fedora/fedora38.0.0.sh && chmod +x fedora38.0.0.sh && ./fedora38.0.0.sh
	;;
        "Kali")
clear
printf "\n"
printf "${wht}Welcome To Kali Termux For Android"
printf "\n\n\n"

printf "${ylw}• Kali Nethunter"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Kali2022\n"
printf "${blu}Versi  ${red}: ${grn}2022.4\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "Kali2022")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Kali/kali2022.sh && chmod +x kali2022.sh && ./kali2022.sh
	;;
        "Parrot")
clear
printf "\n"
printf "${wht}Welcome To Parrot Termux For Android"
printf "\n\n\n"

printf "${ylw}• Parrot 5.1 (Electro Ara)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Parrot5.1\n"
printf "${blu}Versi  ${red}: ${grn}5.1.1\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "Parrot5.1")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Parrot/parrot5.1.1.sh && chmod +x parrot5.1.1.sh && ./parrot5.1.1.sh
	;;
        "Ubuntu")
clear
printf "\n"
printf "${wht}Welcome To Ubuntu Termux For Android"
printf "\n\n\n"
printf "${ylw}• Ubuntu (Lunar Lobster)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Ubuntu23.04\n"
printf "${blu}Versi  ${red}: ${grn}23.04\n"
printf "${blu}Status ${red}: ${grn}Pre-release\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${ylw}• Ubuntu (Kinetic Kudu)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Ubuntu22.10\n"
printf "${blu}Versi  ${red}: ${grn}22.10\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${ylw}• Ubuntu (Jammy Jellyfish)"
printf "\n\n"
printf "${blu}Name   ${red}: ${grn}Ubuntu22.04\n"
printf "${blu}Versi  ${red}: ${grn}22.04.1 lts\n"
printf "${blu}Status ${red}: ${grn}latest\n"
printf "${blu}Rootfs ${red}: ${grn}Armhf,Arm64,Amd64"
printf "\n\n"
printf "${grn}To install run with : Install <${blu}Name${grn}>"
printf "\n\n"
	;;
        "Ubuntu22.04")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Ubuntu/ubuntu22.04.sh && chmod +x ubuntu22.04.sh && ./ubuntu22.04.sh
        ;;
        "Ubuntu22.10")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Ubuntu/ubuntu22.10.sh && chmod +x ubuntu22.10.sh && ./ubuntu22.10.sh
        ;;
        "Ubuntu23.04")
wget https://raw.githubusercontent.com/wahasa/Project/main/Linux/Ubuntu/ubuntu23.04.sh && chmod +x ubuntu23.04.sh && ./ubuntu23.04.sh
	;;
        *)
Linux List
        ;;
esac
