#!/bin/bash
blk='\e[0;30m' red='\e[0;31m' grn='\e[0;32m' ylw='\e[0;33m'
blu='\e[0;34m' pur='\e[0;35m' cyn='\e[0;36m' wht='\e[0;37m'
clear
case "$1" in
        "")
printf "\n"
printf "${ylw}Welcome To Linux Termux For Android"
printf "\n\n\n"
printf "${blu}List of the available commands"
printf "\n\n"
printf "${wht}- ${blu}Linux List   ${wht}: ${blu}To see a list of Linux."
printf "\n"
printf "${wht}- ${blu}Linux Update ${wht}: ${blu}To update Linux list."
printf "\n"
printf "${wht}- ${blu}Linux Help   ${wht}: ${blu}To see all commands."
printf "\n"
printf "${wht}- ${blu}Linux About  ${wht}: ${blu}To see all the information."
printf "\n\n"
printf "${grn}Please run the command above."
printf "\n\n"
        ;;
        "List")
clear
printf "\n"
printf "${ylw}List Linux Termux For Android"
printf "\n\n"
printf "${wht}- ${blu}Alpine"
printf "\n\n"
printf "${wht}- ${blu}Debian"
printf "\n\n"
printf "${wht}- ${blu}Fedora"
printf "\n\n"
printf "${wht}- ${blu}Kali"
printf "\n\n"
printf "${wht}- ${blu}Manjaro"
printf "\n\n"
printf "${wht}- ${blu}Parrot"
printf "\n\n"
printf "${wht}- ${blu}Ubuntu"
printf "\n\n"
printf "${wht}- ${blu}Void"
printf "\n\n"
printf "${grn}Please run the command 'Linux <name linux>' above."
printf "\n\n"
        ;;
        "Update")
clear
wget https://raw.githubusercontent.com/wahasa/Project/main/update.sh && chmod +x update.sh && ./update.sh
	;;
        "Help")
clear
printf "\n"
printf "${ylw}Welcome To Linux Termux For Android"
printf "\n\n\n"
printf "${blu}List of the available commands"
printf "\n\n"
printf "${red}Page 1"
printf "\n\n"
printf "${wht}- ${grn}Linux List   ${wht}: ${blu}To see a list of Linux."
printf "\n"
printf "${wht}- ${grn}Linux Update ${wht}: ${blu}To update Linux list."
printf "\n"
printf "${wht}- ${grn}Linux Help   ${wht}: ${blu}To see all commands."
printf "\n"
printf "${wht}- ${grn}Linux About  ${wht}: ${blu}To see all the information."
printf "\n\n\n"
printf "${red}Page 2"
printf "\n\n"
printf "${wht}- ${grn}Linux <Namelinux>     ${wht}: ${blu}To select the Linux version."
printf "\n\n"
printf "${blu}Example ${wht}: ${grn}Linux Ubuntu"
printf "\n\n"
printf "${wht}- ${grn}Install <Namelinux>   ${wht}: ${blu}Command to install Linux."
printf "\n\n"
printf "${blu}Example ${wht}: ${grn}Install Ubuntu23.04"
printf "\n\n"
printf "${wht}- ${grn}Uninstall <Namelinux> ${wht}: ${blu}Command to uninstall Linux."
printf "\n\n"
printf "${blu}Example ${wht}: ${grn}Uninstall Ubuntu"
printf "\n\n\n"
printf "${red}Page 3"
printf "\n\n"
printf "${wht}• ${blu}Start Linux"
printf "\n"
printf "${wht}- ${grn}<name linux> ${wht}: ${blu}Command to login Linux."
printf "\n\n"
printf "${blu}Example ${wht}: ${grn}ubuntu"
printf "\n\n"
printf "${wht}• ${blu}Stop Linux"
printf "\n"
printf "${wht}- ${grn}exit         ${wht}: ${blu}Command to stop Linux."
printf "\n\n\n"
printf "${grn}Please run the command above."
printf "\n\n"
	;;
        "About")
clear
printf "\n"
printf "${ylw}Welcome To Linux Termux For Android"
printf "\n\n\n"
printf "${blu}Hallo guys,."
printf "\n"
printf "${blu}This time I will make a simple script to install Linux on Termux which I have collected for several Linux,"
printf "\n"
printf "and I will continue to update it if there is the latest rootfs."
printf "\n\n\n"
printf "${blu}Source"
printf "\n"
printf "${grn}Anlinux  ${wht}> ${ylw}https://github.com/EXALAB"
printf "\n"
printf "${grn}Andronix ${wht}> ${ylw}https://github.com/AndronixApp"
printf "\n"
printf "${grn}Docker   ${wht}> ${ylw}https://hub.docker.com"
printf "\n"
printf "${grn}wahasa   ${wht}> ${ylw}https://github.com/wahasa"
printf "\n\n\n"
printf "${blu}My channel"
printf "\n\n"
printf "${grn}Github  ${wht}> ${grn}wahasa"
printf "\n"
printf "${ylw}https://github.com/wahasa"
printf "\n\n"
printf "${grn}Discord ${wht}> ${grn}WaHaSa"
printf "\n"
printf "${ylw}https://discord.gg/GCehyym"
printf "\n\n"
printf "${grn}Youtube ${wht}> ${grn}Layar Geser"
printf "\n"
printf "${ylw}https://youtube.com/@layargeser"
printf "\n\n\n"
printf "${blu}WaHaSa | Layar Geser 2022"
printf "\n\n"
	;;
        "Alpine")
        Install Alpine
;;
        "Arch")
        Linux List
;;
        "Centos")
        Linux List
;;
        "Debian")
        Install Debian
;;
        "Fedora")
        Install Fedora
;;
        "Kali")
        Install Kali
;;
        "Majora")
        Install Manjaro
;;
        "Opensuse")
        Linux List
;;
        "Parrot")
        Install Parrot
;;
        "Ubuntu")
        Install Ubuntu
;;
        "Void")
        Install Void
        ;;
        *)
Linux List
        ;;
esac
